---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	initialize(initialize)
	user_input(user_input)
	ai_response(ai_response)
	__end__([<p>__end__</p>]):::last
	__start__ --> initialize;
	ai_response -. &nbsp;end&nbsp; .-> __end__;
	ai_response -. &nbsp;continue_input&nbsp; .-> user_input;
	initialize --> user_input;
	user_input -. &nbsp;end&nbsp; .-> __end__;
	user_input -.-> ai_response;
	user_input -. &nbsp;continue_input&nbsp; .-> user_input;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
